spring:
  application:
    name: categoria-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mensaje:
  texto: Configuración obtenida desde Config Server para Categoría Service

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
